// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.3
// source: usermgmt/usermgmt.proto

package go_usermgmt_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewCar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NewCar) Reset() {
	*x = NewCar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermgmt_usermgmt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewCar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCar) ProtoMessage() {}

func (x *NewCar) ProtoReflect() protoreflect.Message {
	mi := &file_usermgmt_usermgmt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCar.ProtoReflect.Descriptor instead.
func (*NewCar) Descriptor() ([]byte, []int) {
	return file_usermgmt_usermgmt_proto_rawDescGZIP(), []int{0}
}

func (x *NewCar) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewCar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SlotNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot int32 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (x *SlotNumber) Reset() {
	*x = SlotNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermgmt_usermgmt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotNumber) ProtoMessage() {}

func (x *SlotNumber) ProtoReflect() protoreflect.Message {
	mi := &file_usermgmt_usermgmt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotNumber.ProtoReflect.Descriptor instead.
func (*SlotNumber) Descriptor() ([]byte, []int) {
	return file_usermgmt_usermgmt_proto_rawDescGZIP(), []int{1}
}

func (x *SlotNumber) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermgmt_usermgmt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_usermgmt_usermgmt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_usermgmt_usermgmt_proto_rawDescGZIP(), []int{2}
}

func (x *Id) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllCars struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllCars) Reset() {
	*x = GetAllCars{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermgmt_usermgmt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCars) ProtoMessage() {}

func (x *GetAllCars) ProtoReflect() protoreflect.Message {
	mi := &file_usermgmt_usermgmt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCars.ProtoReflect.Descriptor instead.
func (*GetAllCars) Descriptor() ([]byte, []int) {
	return file_usermgmt_usermgmt_proto_rawDescGZIP(), []int{3}
}

type CarList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cars []*NewCar `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
}

func (x *CarList) Reset() {
	*x = CarList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usermgmt_usermgmt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarList) ProtoMessage() {}

func (x *CarList) ProtoReflect() protoreflect.Message {
	mi := &file_usermgmt_usermgmt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarList.ProtoReflect.Descriptor instead.
func (*CarList) Descriptor() ([]byte, []int) {
	return file_usermgmt_usermgmt_proto_rawDescGZIP(), []int{4}
}

func (x *CarList) GetCars() []*NewCar {
	if x != nil {
		return x.Cars
	}
	return nil
}

var File_usermgmt_usermgmt_proto protoreflect.FileDescriptor

var file_usermgmt_usermgmt_proto_rawDesc = []byte{
	0x0a, 0x17, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x67, 0x6d, 0x74, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x6d,
	0x67, 0x6d, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6d,
	0x67, 0x6d, 0x74, 0x22, 0x2c, 0x0a, 0x06, 0x4e, 0x65, 0x77, 0x43, 0x61, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x20, 0x0a, 0x0a, 0x53, 0x6c, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73,
	0x6c, 0x6f, 0x74, 0x22, 0x14, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x73, 0x22, 0x2f, 0x0a, 0x07, 0x43, 0x61, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x4e, 0x65, 0x77, 0x43,
	0x61, 0x72, 0x52, 0x04, 0x63, 0x61, 0x72, 0x73, 0x32, 0xb5, 0x01, 0x0a, 0x0a, 0x50, 0x61, 0x72,
	0x6b, 0x69, 0x6e, 0x67, 0x4c, 0x6f, 0x74, 0x12, 0x37, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x6b, 0x59,
	0x6f, 0x75, 0x72, 0x43, 0x61, 0x72, 0x12, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x67, 0x6d,
	0x74, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x61, 0x72, 0x1a, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d,
	0x67, 0x6d, 0x74, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x00,
	0x12, 0x32, 0x0a, 0x0d, 0x55, 0x6e, 0x70, 0x61, 0x72, 0x6b, 0x59, 0x6f, 0x75, 0x72, 0x43, 0x61,
	0x72, 0x12, 0x0c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x49, 0x64, 0x1a,
	0x11, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x6b, 0x65,
	0x64, 0x43, 0x61, 0x72, 0x73, 0x12, 0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x67, 0x6d, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x61, 0x72, 0x73, 0x1a, 0x11, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00,
	0x42, 0x2f, 0x5a, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x6f, 0x2d, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x67, 0x6d, 0x74, 0x2d, 0x67, 0x72, 0x70, 0x63,
	0x3b, 0x67, 0x6f, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6d, 0x67, 0x6d, 0x74, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_usermgmt_usermgmt_proto_rawDescOnce sync.Once
	file_usermgmt_usermgmt_proto_rawDescData = file_usermgmt_usermgmt_proto_rawDesc
)

func file_usermgmt_usermgmt_proto_rawDescGZIP() []byte {
	file_usermgmt_usermgmt_proto_rawDescOnce.Do(func() {
		file_usermgmt_usermgmt_proto_rawDescData = protoimpl.X.CompressGZIP(file_usermgmt_usermgmt_proto_rawDescData)
	})
	return file_usermgmt_usermgmt_proto_rawDescData
}

var file_usermgmt_usermgmt_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_usermgmt_usermgmt_proto_goTypes = []interface{}{
	(*NewCar)(nil),     // 0: usermgmt.NewCar
	(*SlotNumber)(nil), // 1: usermgmt.SlotNumber
	(*Id)(nil),         // 2: usermgmt.Id
	(*GetAllCars)(nil), // 3: usermgmt.GetAllCars
	(*CarList)(nil),    // 4: usermgmt.CarList
}
var file_usermgmt_usermgmt_proto_depIdxs = []int32{
	0, // 0: usermgmt.CarList.cars:type_name -> usermgmt.NewCar
	0, // 1: usermgmt.ParkingLot.ParkYourCar:input_type -> usermgmt.NewCar
	2, // 2: usermgmt.ParkingLot.UnparkYourCar:input_type -> usermgmt.Id
	3, // 3: usermgmt.ParkingLot.GetParkedCars:input_type -> usermgmt.GetAllCars
	1, // 4: usermgmt.ParkingLot.ParkYourCar:output_type -> usermgmt.SlotNumber
	4, // 5: usermgmt.ParkingLot.UnparkYourCar:output_type -> usermgmt.CarList
	4, // 6: usermgmt.ParkingLot.GetParkedCars:output_type -> usermgmt.CarList
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_usermgmt_usermgmt_proto_init() }
func file_usermgmt_usermgmt_proto_init() {
	if File_usermgmt_usermgmt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_usermgmt_usermgmt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewCar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermgmt_usermgmt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermgmt_usermgmt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermgmt_usermgmt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllCars); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usermgmt_usermgmt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_usermgmt_usermgmt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usermgmt_usermgmt_proto_goTypes,
		DependencyIndexes: file_usermgmt_usermgmt_proto_depIdxs,
		MessageInfos:      file_usermgmt_usermgmt_proto_msgTypes,
	}.Build()
	File_usermgmt_usermgmt_proto = out.File
	file_usermgmt_usermgmt_proto_rawDesc = nil
	file_usermgmt_usermgmt_proto_goTypes = nil
	file_usermgmt_usermgmt_proto_depIdxs = nil
}
